Route List
+---------------------------------------------+------------------------------------------------------+--------+------------------------------------------------------+--------+
| Rule                                        | Route                                                | Method | Name                                                 | Domain |
+---------------------------------------------+------------------------------------------------------+--------+------------------------------------------------------+--------+
| captcha/<id?>                               | \think\captcha\CaptchaController@index               | get    | \think\captcha\CaptchaController@index               |        |
| api/admin/menu                              | index/Index/menu                                     | *      | index/Index/menu                                     |        |
| api/admin/welcome                           | index/Index/welcome                                  | *      | index/Index/welcome                                  |        |
| api/versions/update                         | index/VersionsManager/update                         | *      | index/VersionsManager/update                         |        |
| api/versions/getServerUrl                   | index/VersionsManager/getServerUrl                   | *      | index/VersionsManager/getServerUrl                   |        |
| api/account/createAccount                   | index/Account/createAccount                          | *      | index/Account/createAccount                          |        |
| api/account/get                             | index/Account/get                                    | *      | index/Account/get                                    |        |
| api/account/addFriend                       | index/Account/addFriend                              | *      | index/Account/addFriend                              |        |
| api/account/acceptInvitation                | index/Account/acceptInvitation                       | *      | index/Account/acceptInvitation                       |        |
| api/account/declineInvitation               | index/Account/declineInvitation                      | *      | index/Account/declineInvitation                      |        |
| api/account/getFriends                      | index/Account/getFriends                             | *      | index/Account/getFriends                             |        |
| api/account/getInfo                         | index/Account/getInfo                                | *      | index/Account/getInfo                                |        |
| api/account/getInfoByCode                   | index/Account/getInfoByCode                          | *      | index/Account/getInfoByCode                          |        |
| api/account/getInfoByPhone                  | index/Account/getInfoByPhone                         | *      | index/Account/getInfoByPhone                         |        |
| api/account/login                           | index/Account/login                                  | *      | index/Account/login                                  |        |
| api/account/admin                           | index/Account/admin                                  | *      | index/Account/admin                                  |        |
| api/account/getInfoByToken                  | index/Account/getInfoByToken                         | *      | index/Account/getInfoByToken                         |        |
| api/account/bindInvitationCode              | index/Account/bindInvitationCode                     | *      | index/Account/bindInvitationCode                     |        |
| api/account/getWhitelist                    | index/Account/getWhitelist                           | *      | index/Account/getWhitelist                           |        |
| api/account/getRoles                        | index/Account/getRoles                               | *      | index/Account/getRoles                               |        |
| api/account/makeWhitelist                   | index/Account/makeWhitelist                          | *      | index/Account/makeWhitelist                          |        |
| api/account/getBlacklist                    | index/Account/getBlacklist                           | *      | index/Account/getBlacklist                           |        |
| api/account/makeBlacklist                   | index/Account/makeBlacklist                          | *      | index/Account/makeBlacklist                          |        |
| api/account/makeAdmin                       | index/Account/makeAdmin                              | *      | index/Account/makeAdmin                              |        |
| api/account/unmakeAdmin                     | index/Account/unmakeAdmin                            | *      | index/Account/unmakeAdmin                            |        |
| api/account/setUserName                     | index/Account/setUserName                            | *      | index/Account/setUserName                            |        |
| api/account/setUserSex                      | index/Account/setUserSex                             | *      | index/Account/setUserSex                             |        |
| api/account/setBirthday                     | index/Account/setBirthday                            | *      | index/Account/setBirthday                            |        |
| api/account/setAvatar                       | index/Account/setAvatar                              | *      | index/Account/setAvatar                              |        |
| api/account/getRoleslist                    | index/Account/getRoleslist                           | *      | index/Account/getRoleslist                           |        |
| api/account/setAdmin                        | index/Account/setAdmin                               | *      | index/Account/setAdmin                               |        |
| api/account/setPassword                     | index/Account/setPassword                            | *      | index/Account/setPassword                            |        |
| api/account/searchKeyword                   | index/Account/searchKeyword                          | *      | index/Account/searchKeyword                          |        |
| api/account/searchuser                      | index/Account/searchuser                             | *      | index/Account/searchuser                             |        |
| api/account/registrationID                  | index/Account/registrationID                         | *      | index/Account/registrationID                         |        |
| api/account/useradmin                       | index/Account/useradmin                              | *      | index/Account/useradmin                              |        |
| api/account/getResidentManager              | index/Account/getResidentManager                     | *      | index/Account/getResidentManager                     |        |
| api/account/getUnresidentManager            | index/Account/getUnresidentManager                   | *      | index/Account/getUnresidentManager                   |        |
| api/account/addResidentManager              | index/Account/addResidentManager                     | *      | index/Account/addResidentManager                     |        |
| api/account/delResidentManager              | index/Account/delResidentManager                     | *      | index/Account/delResidentManager                     |        |
| api/account/getUnadminlist                  | index/Account/getUnadminlist                         | *      | index/Account/getUnadminlist                         |        |
| api/account/setAdminroles                   | index/Account/setAdminroles                          | *      | index/Account/setAdminroles                          |        |
| api/ad/add                                  | index/AdsManager/add                                 | *      | index/AdsManager/add                                 |        |
| api/ad/del                                  | index/AdsManager/del                                 | *      | index/AdsManager/del                                 |        |
| api/ad/update                               | index/AdsManager/update                              | *      | index/AdsManager/update                              |        |
| api/ad/getAdList                            | index/AdsManager/getAdList                           | *      | index/AdsManager/getAdList                           |        |
| api/resumes/get                             | index/ResumesManager/get                             | *      | index/ResumesManager/get                             |        |
| api/resumes/saveBasicInformation            | index/ResumesManager/saveBasicInformation            | *      | index/ResumesManager/saveBasicInformation            |        |
| api/resumes/delBasicInformation             | index/ResumesManager/delBasicInformation             | *      | index/ResumesManager/delBasicInformation             |        |
| api/resumes/saveResumeEducationalExperience | index/ResumesManager/saveResumeEducationalExperience | *      | index/ResumesManager/saveResumeEducationalExperience |        |
| api/resumes/delResumeEducationalExperience  | index/ResumesManager/delResumeEducationalExperience  | *      | index/ResumesManager/delResumeEducationalExperience  |        |
| api/resumes/saveResumeWorkExperience        | index/ResumesManager/saveResumeWorkExperience        | *      | index/ResumesManager/saveResumeWorkExperience        |        |
| api/resumes/delResumeWorkExperience         | index/ResumesManager/delResumeWorkExperience         | *      | index/ResumesManager/delResumeWorkExperience         |        |
| api/captcha/getCaptcha                      | index/captcha/getCaptcha                             | *      | index/captcha/getCaptcha                             |        |
| api/welcome/get                             | index/Welcome/get                                    | *      | index/Welcome/get                                    |        |
| api/upload/one                              | index/Upload/one                                     | *      | index/Upload/one                                     |        |
| api/factory/input                           | index/FactorysManager/input                          | *      | index/FactorysManager/input                          |        |
| api/factory/getInputEvent                   | index/FactorysManager/getInputEvent                  | *      | index/FactorysManager/getInputEvent                  |        |
| api/factory/dele                            | index/FactorysManager/dele                           | *      | index/FactorysManager/dele                           |        |
| api/factory/dispose                         | index/FactorysManager/dispose                        | *      | index/FactorysManager/dispose                        |        |
| api/factory/getlist                         | index/FactorysManager/getlist                        | *      | index/FactorysManager/getlist                        |        |
| api/factory/getInfo                         | index/FactorysManager/getInfo                        | *      | index/FactorysManager/getInfo                        |        |
| api/factory/getImages                       | index/FactorysManager/getImages                      | *      | index/FactorysManager/getImages                      |        |
| api/factory/getTeacherList                  | index/FactorysManager/getTeacherList                 | *      | index/FactorysManager/getTeacherList                 |        |
| api/factory/getAvailableTeacher             | index/FactorysManager/getAvailableTeacher            | *      | index/FactorysManager/getAvailableTeacher            |        |
| api/factory/allotTeacher                    | index/FactorysManager/allotTeacher                   | *      | index/FactorysManager/allotTeacher                   |        |
| api/factory/delTacher                       | index/FactorysManager/delTacher                      | *      | index/FactorysManager/delTacher                      |        |
| api/factory/getFactoryHRList                | index/FactorysManager/getFactoryHRList               | *      | index/FactorysManager/getFactoryHRList               |        |
| api/factory/getAvailableFactoryHR           | index/FactorysManager/getAvailableFactoryHR          | *      | index/FactorysManager/getAvailableFactoryHR          |        |
| api/factory/allotFactoryHR                  | index/FactorysManager/allotFactoryHR                 | *      | index/FactorysManager/allotFactoryHR                 |        |
| api/factory/delFactoryHR                    | index/FactorysManager/delFactoryHR                   | *      | index/FactorysManager/delFactoryHR                   |        |
| api/factory/getCondition                    | index/FactorysManager/getCondition                   | *      | index/FactorysManager/getCondition                   |        |
| api/factory/addTax                          | index/FactorysManager/addTax                         | *      | index/FactorysManager/addTax                         |        |
| api/factory/addTnsurance                    | index/FactorysManager/addTnsurance                   | *      | index/FactorysManager/addTnsurance                   |        |
| api/factory/setSigningInfo                  | index/FactorysManager/setSigningInfo                 | *      | index/FactorysManager/setSigningInfo                 |        |
| api/factory/getJobTypes                     | index/FactorysManager/getJobTypes                    | *      | index/FactorysManager/getJobTypes                    |        |
| api/factory/addJob                          | index/FactorysManager/addJob                         | *      | index/FactorysManager/addJob                         |        |
| api/factory/getAvailableTactorylist         | index/FactorysManager/getAvailableTactorylist        | *      | index/FactorysManager/getAvailableTactorylist        |        |
| api/factory/jobList                         | index/FactorysManager/jobList                        | *      | index/FactorysManager/jobList                        |        |
| api/factory/usableJobList                   | index/FactorysManager/usableJobList                  | *      | index/FactorysManager/usableJobList                  |        |
| api/factory/isHotJob                        | index/FactorysManager/isHotJob                       | *      | index/FactorysManager/isHotJob                       |        |
| api/factory/delJob                          | index/FactorysManager/delJob                         | *      | index/FactorysManager/delJob                         |        |
| api/factory/pushJob                         | index/FactorysManager/pushJob                        | *      | index/FactorysManager/pushJob                        |        |
| api/factory/soldOutJob                      | index/FactorysManager/soldOutJob                     | *      | index/FactorysManager/soldOutJob                     |        |
| api/factory/jobInfo                         | index/FactorysManager/jobInfo                        | *      | index/FactorysManager/jobInfo                        |        |
| api/factory/updateJob                       | index/FactorysManager/updateJob                      | *      | index/FactorysManager/updateJob                      |        |
| api/factory/detailJob                       | index/FactorysManager/detailJob                      | *      | index/FactorysManager/detailJob                      |        |
| api/factory/apply                           | index/FactorysManager/apply                          | *      | index/FactorysManager/apply                          |        |
| api/factory/getApplylist                    | index/FactorysManager/getApplylist                   | *      | index/FactorysManager/getApplylist                   |        |
| api/factory/isApply                         | index/FactorysManager/isApply                        | *      | index/FactorysManager/isApply                        |        |
| api/factory/jobSearch                       | index/FactorysManager/jobSearch                      | *      | index/FactorysManager/jobSearch                      |        |
| api/factory/getFactroyHRInfo                | index/FactorysManager/getFactroyHRInfo               | *      | index/FactorysManager/getFactroyHRInfo               |        |
| api/factory/personnelAudit                  | index/FactorysManager/personnelAudit                 | *      | index/FactorysManager/personnelAudit                 |        |
| api/factory/getLeavelist                    | index/FactorysManager/getLeavelist                   | *      | index/FactorysManager/getLeavelist                   |        |
| api/factory/auditPATeacher                  | index/FactorysManager/auditPATeacher                 | *      | index/FactorysManager/auditPATeacher                 |        |
| api/factory/getReimbursementlist            | index/FactorysManager/getReimbursementlist           | *      | index/FactorysManager/getReimbursementlist           |        |
| api/factory/getQuitlist                     | index/FactorysManager/getQuitlist                    | *      | index/FactorysManager/getQuitlist                    |        |
| api/factory/businessAudit                   | index/FactorysManager/businessAudit                  | *      | index/FactorysManager/businessAudit                  |        |
| api/factory/inJobReview                     | index/FactorysManager/inJobReview                    | *      | index/FactorysManager/inJobReview                    |        |
| api/factory/getStafflist                    | index/FactorysManager/getStafflist                   | *      | index/FactorysManager/getStafflist                   |        |
| api/factory/staffAudit                      | index/FactorysManager/staffAudit                     | *      | index/FactorysManager/staffAudit                     |        |
| api/factory/getStaffInfolist                | index/FactorysManager/getStaffInfolist               | *      | index/FactorysManager/getStaffInfolist               |        |
| api/factory/logs                            | index/FactorysManager/logs                           | *      | index/FactorysManager/logs                           |        |
| api/factory/staffLogs                       | index/FactorysManager/staffLogs                      | *      | index/FactorysManager/staffLogs                      |        |
| api/factory/getAdvancelist                  | index/FactorysManager/getAdvancelist                 | *      | index/FactorysManager/getAdvancelist                 |        |
| api/factory/getAttendancelist               | index/FactorysManager/getAttendancelist              | *      | index/FactorysManager/getAttendancelist              |        |
| api/factory/setAttendance                   | index/FactorysManager/setAttendance                  | *      | index/FactorysManager/setAttendance                  |        |
| api/factory/delAttendance                   | index/FactorysManager/delAttendance                  | *      | index/FactorysManager/delAttendance                  |        |
| api/bank/get                                | index/BankManager/get                                | *      | index/BankManager/get                                |        |
| api/bank/isWorkers                          | index/BankManager/isWorkers                          | *      | index/BankManager/isWorkers                          |        |
| api/system/get                              | index/SystemSetManager/get                           | *      | index/SystemSetManager/get                           |        |
| api/system/updatejobsearch                  | index/SystemSetManager/updatejobsearch               | *      | index/SystemSetManager/updatejobsearch               |        |
| api/system/updatesignin                     | index/SystemSetManager/updatesignin                  | *      | index/SystemSetManager/updatesignin                  |        |
| api/system/updateshare                      | index/SystemSetManager/updateshare                   | *      | index/SystemSetManager/updateshare                   |        |
| api/wallet/getServiceCharge                 | index/WalletManager/getServiceCharge                 | *      | index/WalletManager/getServiceCharge                 |        |
| api/wallet/generalHandlingCharges           | index/WalletManager/generalHandlingCharges           | *      | index/WalletManager/generalHandlingCharges           |        |
| api/wallet/updateCommissionFee              | index/WalletManager/updateCommissionFee              | *      | index/WalletManager/updateCommissionFee              |        |
| api/wallet/getMyWallet                      | index/WalletManager/getMyWallet                      | *      | index/WalletManager/getMyWallet                      |        |
| api/wallet/availableAmount                  | index/WalletManager/availableAmount                  | *      | index/WalletManager/availableAmount                  |        |
| api/wallet/applyForAdvance                  | index/WalletManager/applyForAdvance                  | *      | index/WalletManager/applyForAdvance                  |        |
| api/wallet/isAdvance                        | index/WalletManager/isAdvance                        | *      | index/WalletManager/isAdvance                        |        |
| api/wallet/billingDetailslist               | index/WalletManager/billingDetailslist               | *      | index/WalletManager/billingDetailslist               |        |
| api/wallet/getBanklist                      | index/WalletManager/getBanklist                      | *      | index/WalletManager/getBanklist                      |        |
| api/wallet/getMyCardList                    | index/WalletManager/getMyCardList                    | *      | index/WalletManager/getMyCardList                    |        |
| api/wallet/addCard                          | index/WalletManager/addCard                          | *      | index/WalletManager/addCard                          |        |
| api/wallet/withdrawableSalary               | index/WalletManager/withdrawableSalary               | *      | index/WalletManager/withdrawableSalary               |        |
| api/wallet/rolloutWageToWallet              | index/WalletManager/rolloutWageToWallet              | *      | index/WalletManager/rolloutWageToWallet              |        |
| api/feedbackes/getList                      | index/FeedbackesManager/getList                      | *      | index/FeedbackesManager/getList                      |        |
| api/feedbackes/create                       | index/FeedbackesManager/create                       | *      | index/FeedbackesManager/create                       |        |
| api/events/getEventList                     | index/EventsManager/getEventList                     | *      | index/EventsManager/getEventList                     |        |
| api/events/getEventLogsList                 | index/EventsManager/getEventLogsList                 | *      | index/EventsManager/getEventLogsList                 |        |
| api/events/addRolesApple                    | index/EventsManager/addRolesApple                    | *      | index/EventsManager/addRolesApple                    |        |
| api/events/adminCreateStrategic             | index/EventsManager/adminCreateStrategic             | *      | index/EventsManager/adminCreateStrategic             |        |
| api/events/addRolesSAApple                  | index/EventsManager/addRolesSAApple                  | *      | index/EventsManager/addRolesSAApple                  |        |
| api/events/eventAudit                       | index/EventsManager/eventAudit                       | *      | index/EventsManager/eventAudit                       |        |
| api/events/getSalesmanApplylist             | index/EventsManager/getSalesmanApplylist             | *      | index/EventsManager/getSalesmanApplylist             |        |
| api/events/eventsListByMe                   | index/EventsManager/eventsListByMe                   | *      | index/EventsManager/eventsListByMe                   |        |
| api/events/getJuniorPartnerApplylist        | index/EventsManager/getJuniorPartnerApplylist        | *      | index/EventsManager/getJuniorPartnerApplylist        |        |
| api/events/getSeniorPartnerApplylist        | index/EventsManager/getSeniorPartnerApplylist        | *      | index/EventsManager/getSeniorPartnerApplylist        |        |
| api/events/getStrategicAllianceApplylist    | index/EventsManager/getStrategicAllianceApplylist    | *      | index/EventsManager/getStrategicAllianceApplylist    |        |
| api/events/updateCompanyInfo                | index/EventsManager/updateCompanyInfo                | *      | index/EventsManager/updateCompanyInfo                |        |
| api/events/dele                             | index/EventsManager/dele                             | *      | index/EventsManager/dele                             |        |
| api/events/getStrategiclist                 | index/EventsManager/getStrategiclist                 | *      | index/EventsManager/getStrategiclist                 |        |
| api/events/createCode                       | index/EventsManager/createCode                       | *      | index/EventsManager/createCode                       |        |
| api/events/getJobEvents                     | index/EventsManager/getJobEvents                     | *      | index/EventsManager/getJobEvents                     |        |
| api/articles/getList                        | index/ArticleManager/getList                         | *      | index/ArticleManager/getList                         |        |
| api/articles/getArticlelist                 | index/ArticleManager/getArticlelist                  | *      | index/ArticleManager/getArticlelist                  |        |
| api/articles/add                            | index/ArticleManager/add                             | *      | index/ArticleManager/add                             |        |
| api/articles/del                            | index/ArticleManager/del                             | *      | index/ArticleManager/del                             |        |
| api/articles/save                           | index/ArticleManager/save                            | *      | index/ArticleManager/save                            |        |
| api/articles/details                        | index/ArticleManager/details                         | *      | index/ArticleManager/details                         |        |
| api/articles/buy                            | index/ArticleManager/buy                             | *      | index/ArticleManager/buy                             |        |
| api/signin/add                              | index/SignInManager/add                              | *      | index/SignInManager/add                              |        |
| api/signin/getList                          | index/SignInManager/getList                          | *      | index/SignInManager/getList                          |        |
| api/favorites/add                           | index/FavoritesManager/add                           | *      | index/FavoritesManager/add                           |        |
| api/favorites/isFavorites                   | index/FavoritesManager/isFavorites                   | *      | index/FavoritesManager/isFavorites                   |        |
| api/favorites/del                           | index/FavoritesManager/del                           | *      | index/FavoritesManager/del                           |        |
| api/favorites/getList                       | index/FavoritesManager/getList                       | *      | index/FavoritesManager/getList                       |        |
| api/partner/auditAuniorPartner              | index/PartnerManager/auditAuniorPartner              | *      | index/PartnerManager/auditAuniorPartner              |        |
| api/partner/registrationReview              | index/PartnerManager/registrationReview              | *      | index/PartnerManager/registrationReview              |        |
| api/partner/getList                         | index/PartnerManager/getList                         | *      | index/PartnerManager/getList                         |        |
| api/partner/getMyJuniorPartnerlist          | index/PartnerManager/getMyJuniorPartnerlist          | *      | index/PartnerManager/getMyJuniorPartnerlist          |        |
| api/partner/getMySeniorPartner              | index/PartnerManager/getMySeniorPartner              | *      | index/PartnerManager/getMySeniorPartner              |        |
| api/partner/getMyASPartnerlist              | index/PartnerManager/getMyASPartnerlist              | *      | index/PartnerManager/getMyASPartnerlist              |        |
| api/partner/getMyStafflist                  | index/PartnerManager/getMyStafflist                  | *      | index/PartnerManager/getMyStafflist                  |        |
| api/partner/delete                          | index/PartnerManager/delete                          | *      | index/PartnerManager/delete                          |        |
| api/partner/getMyPWorkerlist                | index/PartnerManager/getMyPWorkerlist                | *      | index/PartnerManager/getMyPWorkerlist                |        |
| api/partner/setStrategicInfo                | index/PartnerManager/setStrategicInfo                | *      | index/PartnerManager/setStrategicInfo                |        |
| api/partner/getStrategiclist                | index/PartnerManager/getStrategiclist                | *      | index/PartnerManager/getStrategiclist                |        |
| api/partner/getStrategicInfor               | index/PartnerManager/getStrategicInfor               | *      | index/PartnerManager/getStrategicInfor               |        |
| api/staff/addFlow                           | index/StaffManager/addFlow                           | *      | index/StaffManager/addFlow                           |        |
| api/staff/getPunchTheClocklist              | index/StaffManager/getPunchTheClocklist              | *      | index/StaffManager/getPunchTheClocklist              |        |
| api/staff/workflowHistory                   | index/StaffManager/workflowHistory                   | *      | index/StaffManager/workflowHistory                   |        |
| api/staff/getSameMonthClocklist             | index/StaffManager/getSameMonthClocklist             | *      | index/StaffManager/getSameMonthClocklist             |        |
| api/staff/advancePayments                   | index/StaffManager/advancePayments                   | *      | index/StaffManager/advancePayments                   |        |
| api/staff/getSameMontcAdvancePayments       | index/StaffManager/getSameMontcAdvancePayments       | *      | index/StaffManager/getSameMontcAdvancePayments       |        |
| api/addres/getAddreslist                    | index/AddresManager/getAddreslist                    | *      | index/AddresManager/getAddreslist                    |        |
| api/addres/delete                           | index/AddresManager/delete                           | *      | index/AddresManager/delete                           |        |
| api/addres/addAddres                        | index/AddresManager/addAddres                        | *      | index/AddresManager/addAddres                        |        |
| api/addres/setAddresDefault                 | index/AddresManager/setAddresDefault                 | *      | index/AddresManager/setAddresDefault                 |        |
| api/rate/getRate                            | index/RateManager/getRate                            | *      | index/RateManager/getRate                            |        |
| api/rate/updateRate                         | index/RateManager/updateRate                         | *      | index/RateManager/updateRate                         |        |
| api/shop/categorylist                       | index/ShopManager/categorylist                       | *      | index/ShopManager/categorylist                       |        |
| api/shop/saveCategory                       | index/ShopManager/saveCategory                       | *      | index/ShopManager/saveCategory                       |        |
| api/shop/delProductsType                    | index/ShopManager/delProductsType                    | *      | index/ShopManager/delProductsType                    |        |
| api/shop/productslist                       | index/ShopManager/productslist                       | *      | index/ShopManager/productslist                       |        |
| api/shop/navitems                           | index/ShopManager/navitems                           | *      | index/ShopManager/navitems                           |        |
| api/shop/arrProducts                        | index/ShopManager/arrProducts                        | *      | index/ShopManager/arrProducts                        |        |
| api/shop/push                               | index/ShopManager/push                               | *      | index/ShopManager/push                               |        |
| api/shop/myProducts                         | index/ShopManager/myProducts                         | *      | index/ShopManager/myProducts                         |        |
| api/shop/setProductsPosition                | index/ShopManager/setProductsPosition                | *      | index/ShopManager/setProductsPosition                |        |
| api/shop/bannerlist                         | index/ShopManager/bannerlist                         | *      | index/ShopManager/bannerlist                         |        |
| api/shop/newArrivals                        | index/ShopManager/newArrivals                        | *      | index/ShopManager/newArrivals                        |        |
| api/shop/goodsByType                        | index/ShopManager/goodsByType                        | *      | index/ShopManager/goodsByType                        |        |
| api/shop/addCard                            | index/ShopManager/addCard                            | *      | index/ShopManager/addCard                            |        |
| api/shop/getCardlist                        | index/ShopManager/getCardlist                        | *      | index/ShopManager/getCardlist                        |        |
| api/shop/deleteCard                         | index/ShopManager/deleteCard                         | *      | index/ShopManager/deleteCard                         |        |
| api/shop/addOrder                           | index/ShopManager/addOrder                           | *      | index/ShopManager/addOrder                           |        |
| api/shop/myOrder                            | index/ShopManager/myOrder                            | *      | index/ShopManager/myOrder                            |        |
| api/shop/signFor                            | index/ShopManager/signFor                            | *      | index/ShopManager/signFor                            |        |
| api/shop/salesRecord                        | index/ShopManager/salesRecord                        | *      | index/ShopManager/salesRecord                        |        |
| api/shop/deliverGoods                       | index/ShopManager/deliverGoods                       | *      | index/ShopManager/deliverGoods                       |        |
| api/shop/orderlist                          | index/ShopManager/orderlist                          | *      | index/ShopManager/orderlist                          |        |
| api/paySlip/addPaySlip                      | index/PaySlipManager/addPaySlip                      | *      | index/PaySlipManager/addPaySlip                      |        |
| api/paySlip/myPaySliplist                   | index/PaySlipManager/myPaySliplist                   | *      | index/PaySlipManager/myPaySliplist                   |        |
| api/paySlip/confirmPaySlip                  | index/PaySlipManager/confirmPaySlip                  | *      | index/PaySlipManager/confirmPaySlip                  |        |
| api/paySlip/getPaySliplist                  | index/PaySlipManager/getPaySliplist                  | *      | index/PaySlipManager/getPaySliplist                  |        |
| api/paySlip/deleteSlip                      | index/PaySlipManager/deleteSlip                      | *      | index/PaySlipManager/deleteSlip                      |        |
| api/paySlip/payWage                         | index/PaySlipManager/payWage                         | *      | index/PaySlipManager/payWage                         |        |
| api/paySlip/getEnterpriseCommission         | index/PaySlipManager/getEnterpriseCommission         | *      | index/PaySlipManager/getEnterpriseCommission         |        |
| api/dividend/getEnterpriseCommission        | index/DividendManager/getEnterpriseCommission        | *      | index/DividendManager/getEnterpriseCommission        |        |
| api/dividend/getCashableCommission          | index/DividendManager/getCashableCommission          | *      | index/DividendManager/getCashableCommission          |        |
| api/dividend/withdrawToLooseChange          | index/DividendManager/withdrawToLooseChange          | *      | index/DividendManager/withdrawToLooseChange          |        |
| api/abonus/get                              | index/AbonusManager/get                              | *      | index/AbonusManager/get                              |        |
| api/pay/singleCash                          | index/DDPayController/singleCash                     | *      | index/DDPayController/singleCash                     |        |
| api/jpush/push                              | index/JPushServers/push                              | *      | index/JPushServers/push                              |        |
| api/jpush/pushAll                           | index/JPushServers/pushAll                           | *      | index/JPushServers/pushAll                           |        |
| api/test/index                              | index/Test/index                                     | *      | index/Test/index                                     |        |
| api/test/userRolesById                      | index/Test/userRolesById                             | *      | index/Test/userRolesById                             |        |
| test/<action>                               | get<action>                                          | get    | get<action>                                          |        |
| test/<action>                               | post<action>                                         | post   | post<action>                                         |        |
| test/<action>                               | put<action>                                          | put    | put<action>                                          |        |
| test/<action>                               | delete<action>                                       | delete | delete<action>                                       |        |
| test/<action>                               | patch<action>                                        | patch  | patch<action>                                        |        |
+---------------------------------------------+------------------------------------------------------+--------+------------------------------------------------------+--------+
